project_id = "duqzvstpszcaxizgmafj"

[functions.suggest-medley]
verify_jwt = false

[functions.import-song]
verify_jwt = false

[functions.mp-checkout]
verify_jwt = true

[functions.mp-webhook]
verify_jwt = false
